/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package io.ballerina.scanner.extension.response;

import java.util.Arrays;

/**
 * Represents the generic response generated by the scanner LS extension.
 */
public abstract class BaseResponse {

    private String errorMsg;
    private String error;
    private String stacktrace;

    public void setError(Throwable e) {
        this.errorMsg = e.getLocalizedMessage();
        // Fallback if message is null
        if (this.errorMsg == null) {
            this.errorMsg = e.getClass().getName();
        }
        this.error = this.errorMsg;
        this.stacktrace = Arrays.toString(e.getStackTrace());
    }

    public void setError(String message) {
        this.errorMsg = message;
        this.error = message;
    }

    public String errorMsg() {
        return errorMsg;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public String getError() {
        return error;
    }

    public String stackTrace() {
        return stacktrace;
    }

    public String getStackTrace() {
        return stacktrace;
    }
}
